name: wise_workout_app
description: Wise Workout Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^7.0.1
  flutter_local_notifications: ^17.0.0
  http: ^1.2.1
  flutter_secure_storage: ^9.2.4
  flutter_facebook_auth: ^6.0.4
  flutter_fortune_wheel: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google-icon.png
    - assets/icons/apple-icon.png
    - assets/icons/facebook-icon.png
    - assets/images/questionnaire_bg.png
    - assets/icons/fitquest-icon.png
    - assets/icons/Home.png
    - assets/icons/Leaderboard.png
    - assets/icons/Messages.png
    - assets/icons/Profile.png
    - assets/images/push-up.jpg
    - assets/images/
