name: wise_workout_app
description: Wise Workout Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^4.3.0
  flutter_local_notifications: ^16.1.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
