name: wise_workout_app
description: Wise Workout Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.1.4                      
  sign_in_with_apple: ^7.0.1             
  flutter_local_notifications: ^17.0.0          
  http: ^1.2.1                                   
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
