name: wise_workout_app
description: Wise Workout Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^7.0.1
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.0 
  flutter_timezone: ^4.1.1
  http: ^1.2.1
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.0
  easy_localization: ^3.0.1
  shared_preferences: ^2.2.3
  youtube_player_iframe: ^5.2.1
  confetti: ^0.7.0
  fl_chart: ^0.64.0
  flutter_datetime_picker_plus: ^2.0.1

  flutter_fortune_wheel: ^1.2.0
  blur: ^4.0.2
  health: ^13.0.1
  share_plus: ^7.2.1
  percent_indicator: ^4.2.3
  circular_countdown_timer: ^0.2.0
  web_socket_channel: ^2.4.0
  camera: ^0.10.5+9
  image: ^4.1.3
  video_player: ^2.8.0
  chewie: ^1.11.3

  flutter_facebook_auth: ^7.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google-icon.png
    - assets/icons/apple-icon.png
    - assets/icons/facebook-icon.png
    - assets/images/questionnaire_bg.png
    - assets/icons/fitquest-icon.png
    - assets/icons/dumbbell.jpg
    - assets/icons/Home.png
    - assets/icons/Leaderboard.png
    - assets/icons/Messages.png
    - assets/icons/Profile.png
    - assets/images/push-up.jpg
    - assets/images/squats.jpg
    - assets/images/plank.jpg
    - assets/images/jumping_jacks.jpg
    - assets/workoutImages/strength_training.jpg
    - assets/workoutImages/yoga_training.jpg
    - assets/workoutImages/core_training.jpg
    - assets/exerciseImages/push_up_gif.jpg
    - assets/exerciseImages/sit_up_gif.jpg
    - assets/exerciseImages/squat_gif.jpg
    - assets/avatars/free/free1.png
    - assets/avatars/free/free2.png
    - assets/avatars/free/free3.png
    - assets/avatars/premium/premium2.png
    - assets/avatars/premium/premium3.png
    - assets/avatars/premium/premium4.png
    - assets/avatars/premium/premium5.png
    - assets/avatars/premium/premium6.png
    - assets/avatars/premium/premium7.png
    - assets/background/bg1.jpg
    - assets/background/bg2.jpg
    - assets/background/bg3.jpeg
    - assets/background/bg4.jpg
    - assets/background/bg5.png
    - assets/background/bg6.png
    - assets/background/bg7.png
    - assets/background/bg8.png
    - assets/background/bg9.png
    - assets/background/black.jpg
    - assets/badges/badge_1.png
    - assets/badges/badge_2.png
    - assets/badges/badge_3.png
    - assets/badges/badge_4.png
    - assets/badges/badge_5.png
    - assets/badges/badge_6.png
    - assets/badges/badge_7.png
    - assets/badges/badge_8.png
    - assets/badges/badge_9.png
    - assets/badges/badge_10.png
    - assets/badges/badge_11.png
    - assets/badges/badge_12.png
    - assets/icons/lock.jpg
    - assets/exerciseGif/push_up.gif
    - assets/exerciseGif/squat.gif
    - assets/workoutImages/dumbbell_strength.jpg
    - assets/workoutImages/evening_wind_down_yoga.jpg
    - assets/workoutImages/leg_day_power_burn.jpg
    - assets/workoutImages/morning_flow_yoga.jpg
    - assets/workoutImages/power_vinyasa.jpg
    - assets/workoutImages/bodyweight_leg_blast.jpg
    - assets/workoutImages/explosive_plyo_legs.jpg
    - assets/workoutImages/glute_isolation_session.jpg
    - assets/workoutImages/quick_hiit_circuit.jpg
    - assets/workoutImages/endurance_cardio_burn.jpg
    - assets/workoutImages/cardio_kickboxing.jpg
    - assets/workoutImages/upper_body_blast.jpg
    - assets/workoutImages/total_body_core_circuit.jpg
    - assets/workoutImages/calisthenics.jpg
    - assets/workoutCategory/cardio.jpg
    - assets/workoutCategory/leg.jpg
    - assets/workoutCategory/push.jpg
    - assets/workoutCategory/relaxing.jpg
    - assets/workoutImages/chest_builder.jpg
    - assets/workoutImages/triceps_shred.jpg
    - assets/workoutImages/upper_body_power.jpg
    - assets/translations/